@startuml
annotation java.lang.Override
class com.google.gson.Gson
class com.google.gson.GsonBuilder
class com.google.gson.TypeAdapter
class com.google.gson.stream.JsonReader
class com.google.gson.stream.JsonWriter
class ec.espe.edu.condominiumManagement.model.Administrator
class ec.espe.edu.condominiumManagement.model.Condominium
class ec.espe.edu.condominiumManagement.model.House
class ec.espe.edu.condominiumManagement.model.Owner
class ec.espe.edu.condominiumManagement.model.ParkingLot
class ec.espe.edu.condominiumManagement.model.Tenant
class ec.espe.edu.condominiumManagement.model.Vehicle
class ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp
class java.io.FileWriter
class java.io.IOException
class java.time.LocalDate
class java.time.Period
class java.time.format.DateTimeFormatter
class java.util.Scanner
class utils.FileManager
ec.espe.edu.condominiumManagement.model.House ..> java.lang.Override
ec.espe.edu.condominiumManagement.model.House ..> java.time.LocalDate
ec.espe.edu.condominiumManagement.model.House ..> java.time.Period
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> java.lang.Override
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> com.google.gson.Gson
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> com.google.gson.GsonBuilder
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> com.google.gson.TypeAdapter
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> com.google.gson.stream.JsonReader
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> com.google.gson.stream.JsonWriter
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> ec.espe.edu.condominiumManagement.model.House
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> java.io.FileWriter
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> java.io.IOException
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> java.time.LocalDate
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> java.time.format.DateTimeFormatter
ec.espe.edu.condominiumManagement.view.CondominiumSimulatorApp ..> java.util.Scanner
@enduml